In [1]:
# import Libraries
import pickle
import json
import pandas as pd
import numpy as np

In [3]:
# Load semua file

# Load numerical columns
with open('list_num_cols.txt', 'r') as file_1:
  num_col = json.load(file_1)

# Load scaler
with open('scaler.pkl', 'rb') as file_2:
  scaler = pickle.load(file_2)

# Load PCA
with open('pca.pkl', 'rb') as file_3:
  pca = pickle.load(file_3)

# Load KMeans
with open('kmeans.pkl', 'rb') as file_4:
  km_elbow = pickle.load(file_4)

In [9]:
# melihat kolom apa saja yang ada di num_col
num_col

['CUST_ID',
 'BALANCE',
 'BALANCE_FREQUENCY',
 'PURCHASES',
 'ONEOFF_PURCHASES',
 'INSTALLMENTS_PURCHASES',
 'CASH_ADVANCE',
 'PURCHASES_FREQUENCY',
 'ONEOFF_PURCHASES_FREQUENCY',
 'PURCHASES_INSTALLMENTS_FREQUENCY',
 'CASH_ADVANCE_FREQUENCY',
 'CASH_ADVANCE_TRX',
 'PURCHASES_TRX',
 'CREDIT_LIMIT',
 'PAYMENTS',
 'MINIMUM_PAYMENTS',
 'PRC_FULL_PAYMENT',
 'TENURE']

In [5]:
# masukkan data inferense
data={
       'CUST_ID': [123,321,213,312],
       'BALANCE': [2347,725,324,5566],
       'BALANCE_FREQUENCY': [1,0.7,0.9,1],
       'PURCHASES': [474, 274, 1226, 7336],
       'ONEOFF_PURCHASES': [293, 210, 592, 5000],
       'INSTALLMENTS_PURCHASES': [181, 63, 663, 2100],
       'CASH_ADVANCE': [4386, 559, 224, 700],
       'PURCHASES_FREQUENCY': [0.2, 0.2, 1, 1],
       'ONEOFF_PURCHASES_FREQUENCY': [0.1, 0.1, 0.2, 0.5],
       'PURCHASES_INSTALLMENTS_FREQUENCY': [0.2, 1, 1, 0.6],
       'CASH_ADVANCE_FREQUENCY': [0.5, 0.1, 0, 0],
       'CASH_ADVANCE_TRX': [14, 3, 5, 2],
       'PURCHASES_TRX': [8, 5, 22, 80],
       'CREDIT_LIMIT': [7352, 4000, 4100, 9000],
       'PAYMENTS': [3272, 900, 1000, 7000],
       'MINIMUM_PAYMENTS': [1962, 500, 600, 2000],
       'PRC_FULL_PAYMENT': [0, 0, 0.5, 1],
       'TENURE': [11, 10, 11, 12]
       }
data_inf = pd.DataFrame(data)
data_inf

,CUST_ID,BALANCE,BALANCE_FREQUENCY,PURCHASES,ONEOFF_PURCHASES,INSTALLMENTS_PURCHASES,CASH_ADVANCE,PURCHASES_FREQUENCY,ONEOFF_PURCHASES_FREQUENCY,PURCHASES_INSTALLMENTS_FREQUENCY,CASH_ADVANCE_FREQUENCY,CASH_ADVANCE_TRX,PURCHASES_TRX,CREDIT_LIMIT,PAYMENTS,MINIMUM_PAYMENTS,PRC_FULL_PAYMENT,TENURE
0,123,2347,1.0,474,293,181,4386,0.2,0.1,0.2,0.5,14,8,7352,3272,1962,0.0,11
1,321,725,0.7,274,210,63,559,0.2,0.1,1.0,0.1,3,5,4000,900,500,0.0,10
2,213,324,0.9,1226,592,663,224,1.0,0.2,1.0,0.0,5,22,4100,1000,600,0.5,11
3,312,5566,1.0,7336,5000,2100,700,1.0,0.5,0.6,0.0,2,80,9000,7000,2000,1.0,12

Diatas sudah terlihat data yang ingin kita coba analisis menggunakan model yang sudah kita buat untuk memprediksi apakah dia termasuk ke dalam cluster 1,2,3 atau 4

In [6]:
# kita scaling terlebih dahulu
data_inf_scaled = scaler.transform(data_inf)
data_inf_scaled

array([[-1.68444364e+00,  3.78313007e-01,  5.16661920e-01,
        -2.56942507e-01, -1.83500077e-01, -2.56738815e-01,
         1.65114164e+00, -7.21287327e-01, -3.43097771e-01,
        -4.12231220e-01,  1.81016850e+00,  1.49970239e+00,
        -2.71327941e-01,  7.91695404e-01,  5.41829615e-01,
         4.66081807e-01, -5.19718254e-01, -3.89992177e-01],
       [-1.60780765e+00, -4.04575705e-01, -7.42806669e-01,
        -3.54039098e-01, -2.33704486e-01, -3.90722944e-01,
        -2.06428926e-01, -7.21287327e-01, -3.43097771e-01,
         1.60005214e+00, -1.79751598e-01, -4.22248434e-02,
        -3.88800129e-01, -1.37128629e-01, -2.97128041e-01,
        -1.43248971e-01, -5.19718254e-01, -1.14256440e+00],
       [-1.64960910e+00, -5.98125874e-01,  9.68390566e-02,
         1.08140676e-01, -2.64322753e-03,  2.90552289e-01,
        -3.69033092e-01,  1.26450557e+00, -7.71851854e-03,
         1.60005214e+00, -6.77231622e-01,  2.38125563e-01,
         2.76875603e-01, -1.09419082e-01, -2.61758831e-01,
        -1.01571080e-01,  1.21009588e+00, -3.89992177e-01],
       [-1.61129110e+00,  1.93202371e+00,  5.16661920e-01,
         3.07444154e+00,  2.66363433e+00,  1.92220647e+00,
        -1.37989561e-01,  1.26450557e+00,  9.98419238e-01,
         5.93910458e-01, -6.77231622e-01, -1.82400047e-01,
         2.54800457e+00,  1.24834875e+00,  1.86039375e+00,
         4.81919406e-01,  2.93991001e+00,  3.62580049e-01]])

In [7]:
# melakukan pca
data_inf_scaled_pca = pca.transform(data_inf_scaled)
data_inf_scaled_pca

array([[-0.63795317,  3.12297774, -0.30650238, -0.8378679 , -0.25880218,
        -1.36176719, -0.62250667, -0.0723232 ,  0.34935402, -0.06144269,
        -0.0155439 ],
       [-0.8096324 , -0.58065329, -0.3709454 , -0.7898172 ,  0.54413615,
        -1.30824556, -1.29018572, -0.0281934 , -0.56154341,  0.24321966,
        -0.74503741],
       [ 1.10189835, -1.46444292, -1.15857448, -1.25850319, -0.10417211,
        -1.50316268, -0.38773168,  0.32455149,  0.51663158,  0.08979264,
        -0.45881677],
       [ 6.23788941,  0.35595545,  1.20500045, -0.47941048,  0.40660981,
        -1.62177774, -0.21884752,  0.83766441,  1.30082617, -1.0809594 ,
         0.48441825]])

In [8]:
# baru kita prediksi data tersebut menggunakan model kita
pred = km_elbow.predict(data_inf_scaled_pca)
pred

array([0, 1, 2, 3], dtype=int32)

Didapatkan bahwa dari data yang telah kita coba menggunakan model kita customer id 123 termasuk kepada cluster pertama yang tergolong "Cautious Spenders", untuk customer id 321 termasuk ke cluster ke 2 yaitu "Inactive Users", untuk id 213 termasuk kepada "Regular Users", dan yang terakhir id 312 termasuk kepada cluster ke 4 yaitu "BIg Spender".